### ISSUE TITLE
Inquiry about enm-cli

### ISSUE THREAD

**Issue by syllith** [vvsviridov/enm-cli#1]
Hello, I came across this package and I'm hoping you could help me out with some problems I am having. I attempted to send an email, but I'm not sure if you received it. If you get this message, could you please let me know? I want to make sure I can contact you before explaining my issue in detail. Thank you!

**Comment by vvsviridov** [comment]
Hi, I received it



Отправлено из мобильной Почты Mail.ru


четверг, 13 октября 2022 г., 20:37 +0600 от ***@***.***  ***@***.***>:

**Comment by syllith** [comment]
Great, nice to meet you! My question is actually unrelated to enm-cli, I am looking for a certain file that I believe you may have access to. I need to find the JAR file for Ericsson's ECT program (Equipment Configuration Tool). I work for AT&T and I need to create a configuration for a baseband unit so that we can power up an Ericsson radio and enable the RF output so that we can test that it works before we ship it out to them. We wouldn't want to install a radio on a tower without confirming it works first.

However, it's proving difficult to find this file online and was hoping you might have access to this tool? It looks like you work in the industry based on what you have created, so I'm hoping you can help. I have attached some screenshots of it in case you are not sure what program I am referring to. Could you perhaps help provide this file or point me in the right direction of where I can get it? I've been looking for this for a long time, so I'm a bit desperate. Thank you for your time!
![ss1](https://user-images.githubusercontent.com/42996651/195656329-5718d226-d348-4277-af63-c13a7ae0497a.png)
![ss2](https://user-images.githubusercontent.com/42996651/195656330-800dd945-c62d-4203-acae-f0eda8e61b9b.png)
![ss3](https://user-images.githubusercontent.com/42996651/195656319-18a66da7-a0cb-4a90-aa3e-09b426bf7b04.png)
![ss4](https://user-images.githubusercontent.com/42996651/195656327-7fa639f0-3f1e-4cac-af4c-583f41fa77cd.png)

**Comment by vvsviridov** [comment]
Nice to meet you too. Sorry, I don't have it. Looks like its Ericsson internal tool.
