### ISSUE TITLE
CM Bulk Import API

### ISSUE THREAD

**Issue by kolayne2021** [vvsviridov/enm-cli#2]
Добрый день! 

Есть небольшой вопрос по добавлению файла в Import job ENM:

Есть код: 

`
    
    def attach_file_to_import_job(self, id: int, filename: str, path: str):
        '''
        Attaches an import file to an existing import job that was created using this NBI. An import job executes operations according to the contents of the import file. 
            Supported file types are 3GPP, EDFF and .zip folders containing an import file
        '''
        data = {"filename": filename, "file": path}
        url = f"https://{self.enm}.test.com/bulk-configuration/v1/import-jobs/jobs/{id}/files"
        resp = self.post(url, data=json.dumps(data))
        return resp
`

Делаю через python request session:

`
class EnmBulkCM(Session):

    def __init__(self, enm: str) -> None:
        super().__init__()
        config = ConfigParser()
        config.read('settings.ini')
        self.user = config[enm]['user']
        self.password = config[enm]['password']
        self.enm = enm
        self.url = f'https://{enm}.test.com/login?IDToken1={self.user}&IDToken2={self.password}'
        self.headers.update({"Content-Type": "application/json", "Accept": "application/json"})
        self.verify = False
        requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
        response = self.post(self.url)
        if response.status_code != requests.codes.ok:
            raise HTTPError("Не могу подключиться к ENM")
`

Упорно получаю ошибку 415 при попытке добавить файл в проект. Да файл типа dff 

Вы не раелизовывали это дело на python случаем? Может есть какая хитрость?

**Comment by vvsviridov** [comment]
@kolayne2021 Привет, да у меня вот так:
```python
    def send_file_to_job(self, request_body, jobid):
        url = f"{self.enm}bulk-configuration/v1/import-jobs/jobs/{jobid}/files"
        self.headers.update({
            "Content-Type": "multipart/form-data",
        })
        with open('qos_bb_1209023901.xml', 'rb') as files:
            resp = self.post(url, files={'file': files})
        return resp
```

**Comment by kolayne2021** [comment]
Спасибо!
